In [2]:
import tensorflow as tf
import numpy as np

Creating tensor

In [4]:
a_constant = tf.constant([1,2,3,4])
a_constant

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [7]:
a_variable = tf.Variable([1,2,3,4])
a_variable

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [8]:
a_range = tf.range(1,10,2)
a_range

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

Scalar: tensor whoes rank is 0

In [32]:
a = tf.constant(3, dtype=float)
a

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

Vector :  tensor whoes rank is 1

In [31]:
b = tf.constant([1.1,2.2,3.3])
b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.1, 2.2, 3.3], dtype=float32)>

Matrix :  tensor whoes rank is 2

In [51]:
c = tf.constant([[1,2,3],[4,5,6]], name="Matrix")
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

Rank

In [52]:
print("Rank of scalar", tf.rank(a), a.shape, tf.size(a))
print("Rank of vector", tf.rank(b), b.shape, tf.size(b))
print("Rank of Matrix", tf.rank(c), c.shape, tf.size(c))

Rank of scalar tf.Tensor(0, shape=(), dtype=int32) () tf.Tensor(1, shape=(), dtype=int32)
Rank of vector tf.Tensor(1, shape=(), dtype=int32) (3,) tf.Tensor(3, shape=(), dtype=int32)
Rank of Matrix tf.Tensor(2, shape=(), dtype=int32) (2, 3) tf.Tensor(6, shape=(), dtype=int32)


# Tensor Basic Operation
 Changing data types

In [53]:
a

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [56]:
a = tf.cast(a, dtype=tf.int32)
a.dtype

tf.int32

Indexing

In [57]:
a_index = tf.constant([[1,2,3,4],[5,6,7,8]])
a_index

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [65]:
a_index[1,1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 7], dtype=int32)>

Tensor aggregation

In [66]:
import random

In [68]:
random.seed(108)
a = random.sample(range(1,100), 50)
a = tf.constant(a)
a

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([17, 92, 11, 85, 50, 94, 36, 49, 26, 97, 39, 28, 24, 91, 41, 25, 15,
       84, 90, 72, 55, 14, 69, 42, 95, 88,  8, 58,  5, 45, 43, 31, 86, 66,
       63, 74,  2, 71, 68, 59, 80, 75, 57, 37, 73, 67, 12, 22, 16, 70],
      dtype=int32)>

In [72]:
print("The samllest number:", tf.reduce_min(a))
print("The largest number:", tf.reduce_max(a))
print("The mean of the numbers:", tf.reduce_mean(a))
print("The sum of the numbers:", tf.reduce_sum(a))

The samllest number: tf.Tensor(2, shape=(), dtype=int32)
The largest number: tf.Tensor(97, shape=(), dtype=int32)
The mean of the numbers: tf.Tensor(52, shape=(), dtype=int32)
The sum of the numbers: tf.Tensor(2617, shape=(), dtype=int32)


In [73]:
print("Index of the samllest number", tf.argmin(a))
print("Index of the largest number", tf.argmax(a))

Index of the samllest number tf.Tensor(36, shape=(), dtype=int64)
Index of the largest number tf.Tensor(9, shape=(), dtype=int64)


 Transposing and reshaping tensors

In [74]:
matrix = tf.constant([[1,2,3,4],[5,6,7,8]])
matrix

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [75]:
tf.reshape(matrix, (2,2,2)) #2*2*2 = 8

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [76]:
tf.transpose(matrix)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]], dtype=int32)>

Matrix multiplication

In [80]:
a = tf.constant([[1,2,3],[4,5,6]])
b = tf.constant([[1,2],[3,4],[5,6]])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [85]:
c = tf.matmul(a,b)
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [86]:
tf.argmax(c)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>